### ISSUE TITLE
Not following contructor pattern

### ISSUE THREAD

**Issue by alexbeletsky** [TiddoLangerak/webpack-fail-plugin#5]
Just a question - all plugins I work with are created with `new` statement, except this one. So, config fine looks like,

``` js
    // ...

    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        dead_code: true,
        drop_debugger: true,
        drop_console: true
      },
      minimize: true,
      sourceMap: true
    }),

    new CopyWebpackPlugin([ {
      from: './source/images',
      to: './images'
    } ]),

  WebpackFailPlugin

   // ...
```

That's a bit inconsistent as for me, are there any reasons to expose a constructor function?

**Comment by TiddoLangerak** [comment]
Webpack requires plugins to be passed as some object where it can call `apply` on. Most plugins accept some form of configuration that it needs to construct this object, and most plugins have chosen to use a constructor to get this done (presumably because the Webpack plugin guide uses this in its example as well). The Webpack fail plugin is so simple though that we really don't have any setup logic, and thus directly expose the plugin object.

On hindsight it would've been nice if this plugin also used the constructor pattern for consistency, but changing this now would unfortunately break the plugin for current users.
