### ISSUE TITLE
webpack-fail-plugin should be a PR, not a plugin

### ISSUE THREAD

**Issue by alexch** [TiddoLangerak/webpack-fail-plugin#9]
Please submit this code change to the https://github.com/webpack/webpack repo as a fix for https://github.com/webpack/webpack/issues/708

**Comment by TiddoLangerak** [comment]
I totally agree, but don't expect that to happen anytime soon (at least, not by me). Submitting this as a PR means that I would need to figure out the internal structure of webpack, adjust the plugin to fit into it, test it from within webpack, and go through all the politics of whether this should be default behavior/opt-in/opt-out. All of that costs time, which unfortunately is a very limited resource for me...

**Comment by TheLarkInn** [comment]
Do you need some guidance for this? I can happily point you in the right direction.

**Comment by TiddoLangerak** [comment]
Thanks for the offer, but I still lack the time to work on this (and frankly it is also really low on my priority list, especially considering that this has been fixed already for Webpack 2). Of course anyone is free to take the changes here and submit them to the Webpack repo themselves, but it's just not something I'm going to put any effort in right now.

**Comment by ChrisKitching** [comment]
A PR to do this has been submitted before, they basically said "no, because webpack 2":
https://github.com/webpack/webpack/issues/708

:disappointed:

**Comment by unional** [comment]
Does it mean I don't need to use this library for webpack 2?

**Comment by lddubeau** [comment]
@unional Yes, that's what it means. Webpack 2 will exit with a non-zero code if it "finishes with errors". Note that if you are invoking Webpack from Gulp, Grunt or something similar, *you are responsible for passing the failure up the chain* (to Gulp, Grunt, etc.) I'm mentioning this because I've seen a number of posts (elsewhere) showing incorrect Gulp code (or Grunt code, or whatever) and then putting the blame on Webpack when the failure got swallowed.
